// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';
import {app} from '../models';
import {drive} from '../models';
import {model} from '../models';
import {sync} from '../models';

export function AddFavorite(arg1:string,arg2:string,arg3:store.Favorite):Promise<void>;

export function ApplyUpdate(arg1:string):Promise<void>;

export function CancelDownload(arg1:string):Promise<void>;

export function CancelMigrate(arg1:string):Promise<void>;

export function CancelSync(arg1:string):Promise<boolean>;

export function CancelUpload(arg1:string):Promise<void>;

export function CheckUpdate():Promise<app.CheckUpdateResult>;

export function ClearCache():Promise<void>;

export function ClearDownloads():Promise<void>;

export function ClearLogs():Promise<void>;

export function ClearMigrateJobs():Promise<void>;

export function ClearUploads():Promise<void>;

export function ClosePikPakCaptcha():Promise<void>;

export function CopyFiles(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<Array<string>>;

export function CreateShare(arg1:string,arg2:string,arg3:drive.ShareParams):Promise<model.ShareItem>;

export function DeleteDirectoryCache(arg1:string):Promise<void>;

export function DeleteFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<Array<string>>;

export function DeleteLocalTag(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteMigrateJob(arg1:string):Promise<void>;

export function DeleteOfflineTask(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function DeleteSyncConfig(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string,arg3:model.File):Promise<model.DownloadTask>;

export function DownloadURL(arg1:string,arg2:string,arg3:Record<string, string>):Promise<model.DownloadTask>;

export function DownloadUpdate(arg1:string):Promise<string>;

export function ExportLogs():Promise<string>;

export function FavoriteFiles(arg1:string,arg2:string,arg3:boolean,arg4:Array<string>):Promise<Array<string>>;

export function ForceQuit():Promise<void>;

export function GetDirectoryCache(arg1:string):Promise<Array<model.File>>;

export function GetDownloadURL(arg1:string,arg2:string,arg3:string):Promise<model.DownloadURL>;

export function GetFileDetail(arg1:string,arg2:string,arg3:string):Promise<model.File>;

export function GetLogPath():Promise<string>;

export function GetPan189Captcha():Promise<string>;

export function GetPlayCursor(arg1:string,arg2:string,arg3:string):Promise<number>;

export function GetSettings():Promise<store.Settings>;

export function GetVideoPreview(arg1:string,arg2:string,arg3:string):Promise<model.VideoPreview>;

export function ImportShare(arg1:string,arg2:string,arg3:string,arg4:string):Promise<drive.ShareImportSession>;

export function ListAccounts():Promise<Array<model.Account>>;

export function ListDir(arg1:string,arg2:string,arg3:string):Promise<Array<model.File>>;

export function ListDirPage(arg1:string,arg2:string,arg3:string,arg4:string):Promise<drive.DirPage>;

export function ListDownloads():Promise<Array<model.DownloadTask>>;

export function ListFavorites(arg1:string,arg2:string):Promise<Array<store.Favorite>>;

export function ListLocalTags(arg1:string,arg2:string):Promise<Array<store.LocalTag>>;

export function ListMigrateJobs():Promise<Array<model.MigrateJob>>;

export function ListOfflineTasks(arg1:string):Promise<Array<model.OfflineTask>>;

export function ListProviders():Promise<Array<app.ProviderInfo>>;

export function ListRunningSyncIDs():Promise<Array<string>>;

export function ListShareHistory(arg1:string):Promise<Array<model.ShareHistoryEntry>>;

export function ListSyncConfigs():Promise<Array<sync.Config>>;

export function ListTrash(arg1:string,arg2:string):Promise<Array<model.File>>;

export function ListUploads():Promise<Array<model.UploadingUI>>;

export function LocalPreviewURL(arg1:string):Promise<string>;

export function LogFrontend(arg1:string,arg2:string,arg3:string,arg4:Record<string, string>):Promise<void>;

export function MediaProxy():Promise<string>;

export function MigrateFiles(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:Array<string>,arg7:boolean):Promise<model.MigrateJob>;

export function Mkdir(arg1:string,arg2:string,arg3:string,arg4:string):Promise<drive.MkdirResult>;

export function MoveFiles(arg1:string,arg2:string,arg3:Array<string>,arg4:string):Promise<Array<string>>;

export function OfflineDownload(arg1:string,arg2:string,arg3:string,arg4:string):Promise<model.OfflineTask>;

export function OpenBrowser(arg1:string):Promise<void>;

export function OpenFile(arg1:string):Promise<void>;

export function OpenPikPakCaptcha(arg1:string):Promise<void>;

export function PauseDownload(arg1:string):Promise<void>;

export function PickDirectory(arg1:string,arg2:string):Promise<string>;

export function PickFiles(arg1:string):Promise<Array<string>>;

export function PinFileSnapshot(arg1:string,arg2:string,arg3:model.File):Promise<void>;

export function PlayVideo(arg1:string,arg2:string,arg3:string):Promise<model.VideoPreview>;

export function PlayVideoQuality(arg1:string,arg2:string,arg3:string,arg4:string):Promise<model.VideoPreview>;

export function PreviewURL(arg1:string,arg2:string,arg3:string):Promise<string>;

export function PrioritizeDownload(arg1:string):Promise<void>;

export function ProviderLogin(arg1:string,arg2:Record<string, string>):Promise<model.Account>;

export function RefreshAccount(arg1:string):Promise<model.Account>;

export function RefreshOfflineTasks(arg1:string,arg2:string):Promise<Array<model.OfflineTask>>;

export function RemoveAccount(arg1:string):Promise<void>;

export function RemoveDownload(arg1:string):Promise<void>;

export function RemoveFavorite(arg1:string,arg2:string,arg3:string):Promise<void>;

export function RenameBatch(arg1:string,arg2:string,arg3:Array<drive.FileRef>,arg4:Array<string>):Promise<Array<drive.RenameResult>>;

export function RenameFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<drive.RenameResult>;

export function RestoreFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<Array<string>>;

export function ResumeDownload(arg1:string):Promise<void>;

export function ResumeUpload(arg1:string):Promise<void>;

export function RevealInFolder(arg1:string):Promise<void>;

export function RunSync(arg1:string):Promise<void>;

export function SaveCloudTextFile(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SaveDirectoryCache(arg1:string,arg2:Array<model.File>):Promise<void>;

export function SaveImportedShare(arg1:string,arg2:string,arg3:drive.ShareImportSession,arg4:Array<string>,arg5:string):Promise<Array<string>>;

export function SaveLocalTag(arg1:store.LocalTag):Promise<void>;

export function SaveMountedAccount(arg1:string,arg2:model.ConnConfig):Promise<model.Account>;

export function SavePlayCursor(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function SaveSettings(arg1:store.Settings):Promise<void>;

export function SaveSyncConfig(arg1:sync.Config):Promise<void>;

export function SearchFiles(arg1:string,arg2:string,arg3:string):Promise<Array<model.File>>;

export function SendGuangyaSms(arg1:string):Promise<Record<string, string>>;

export function SetupFloater(arg1:Array<number>):Promise<void>;

export function SetupTray(arg1:Array<number>):Promise<void>;

export function ShowMainWindow():Promise<void>;

export function StartSyncScheduler():Promise<string>;

export function TrashFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<Array<string>>;

export function UploadFiles(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<Array<model.UploadingUI>>;

export function WatchShowRequests():Promise<void>;
