// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavorite(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddFavorite'](arg1, arg2, arg3);
}

export function CancelDownload(arg1) {
  return window['go']['app']['App']['CancelDownload'](arg1);
}

export function CancelUpload(arg1) {
  return window['go']['app']['App']['CancelUpload'](arg1);
}

export function ClearDownloads() {
  return window['go']['app']['App']['ClearDownloads']();
}

export function ClearUploads() {
  return window['go']['app']['App']['ClearUploads']();
}

export function CopyFiles(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CopyFiles'](arg1, arg2, arg3, arg4);
}

export function CreateShare(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateShare'](arg1, arg2, arg3);
}

export function DeleteFiles(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteFiles'](arg1, arg2, arg3);
}

export function DeleteLocalTag(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteLocalTag'](arg1, arg2, arg3);
}

export function DeleteSyncConfig(arg1) {
  return window['go']['app']['App']['DeleteSyncConfig'](arg1);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function DownloadURL(arg1, arg2, arg3) {
  return window['go']['app']['App']['DownloadURL'](arg1, arg2, arg3);
}

export function FavoriteFiles(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['FavoriteFiles'](arg1, arg2, arg3, arg4);
}

export function GetDownloadURL(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetDownloadURL'](arg1, arg2, arg3);
}

export function GetFileDetail(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetFileDetail'](arg1, arg2, arg3);
}

export function GetPlayCursor(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetPlayCursor'](arg1, arg2, arg3);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetVideoPreview(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetVideoPreview'](arg1, arg2, arg3);
}

export function ListAccounts() {
  return window['go']['app']['App']['ListAccounts']();
}

export function ListDir(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListDir'](arg1, arg2, arg3);
}

export function ListDirPage(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ListDirPage'](arg1, arg2, arg3, arg4);
}

export function ListDownloads() {
  return window['go']['app']['App']['ListDownloads']();
}

export function ListFavorites(arg1, arg2) {
  return window['go']['app']['App']['ListFavorites'](arg1, arg2);
}

export function ListLocalTags(arg1, arg2) {
  return window['go']['app']['App']['ListLocalTags'](arg1, arg2);
}

export function ListOfflineTasks(arg1) {
  return window['go']['app']['App']['ListOfflineTasks'](arg1);
}

export function ListProviders() {
  return window['go']['app']['App']['ListProviders']();
}

export function ListShareHistory(arg1) {
  return window['go']['app']['App']['ListShareHistory'](arg1);
}

export function ListSyncConfigs() {
  return window['go']['app']['App']['ListSyncConfigs']();
}

export function ListTrash(arg1, arg2) {
  return window['go']['app']['App']['ListTrash'](arg1, arg2);
}

export function ListUploads() {
  return window['go']['app']['App']['ListUploads']();
}

export function LocalPreviewURL(arg1) {
  return window['go']['app']['App']['LocalPreviewURL'](arg1);
}

export function MediaProxy() {
  return window['go']['app']['App']['MediaProxy']();
}

export function MigrateFiles(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['MigrateFiles'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function Mkdir(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Mkdir'](arg1, arg2, arg3, arg4);
}

export function MoveFiles(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['MoveFiles'](arg1, arg2, arg3, arg4);
}

export function OfflineDownload(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['OfflineDownload'](arg1, arg2, arg3, arg4);
}

export function OpenBrowser(arg1) {
  return window['go']['app']['App']['OpenBrowser'](arg1);
}

export function PauseDownload(arg1) {
  return window['go']['app']['App']['PauseDownload'](arg1);
}

export function PausePlayer(arg1) {
  return window['go']['app']['App']['PausePlayer'](arg1);
}

export function PlayVideo(arg1, arg2, arg3) {
  return window['go']['app']['App']['PlayVideo'](arg1, arg2, arg3);
}

export function PreviewURL(arg1, arg2, arg3) {
  return window['go']['app']['App']['PreviewURL'](arg1, arg2, arg3);
}

export function ProviderLogin(arg1, arg2) {
  return window['go']['app']['App']['ProviderLogin'](arg1, arg2);
}

export function RemoveAccount(arg1) {
  return window['go']['app']['App']['RemoveAccount'](arg1);
}

export function RemoveFavorite(arg1, arg2, arg3) {
  return window['go']['app']['App']['RemoveFavorite'](arg1, arg2, arg3);
}

export function RenameBatch(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RenameBatch'](arg1, arg2, arg3, arg4);
}

export function RenameFile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RenameFile'](arg1, arg2, arg3, arg4);
}

export function RestoreFiles(arg1, arg2, arg3) {
  return window['go']['app']['App']['RestoreFiles'](arg1, arg2, arg3);
}

export function ResumeDownload(arg1) {
  return window['go']['app']['App']['ResumeDownload'](arg1);
}

export function RunSync(arg1) {
  return window['go']['app']['App']['RunSync'](arg1);
}

export function SaveLocalTag(arg1) {
  return window['go']['app']['App']['SaveLocalTag'](arg1);
}

export function SaveMountedAccount(arg1, arg2) {
  return window['go']['app']['App']['SaveMountedAccount'](arg1, arg2);
}

export function SavePlayCursor(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SavePlayCursor'](arg1, arg2, arg3, arg4);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SaveSyncConfig(arg1) {
  return window['go']['app']['App']['SaveSyncConfig'](arg1);
}

export function SearchFiles(arg1, arg2, arg3) {
  return window['go']['app']['App']['SearchFiles'](arg1, arg2, arg3);
}

export function SeekPlayer(arg1) {
  return window['go']['app']['App']['SeekPlayer'](arg1);
}

export function SendGuangyaSms(arg1) {
  return window['go']['app']['App']['SendGuangyaSms'](arg1);
}

export function SetPlayerSpeed(arg1) {
  return window['go']['app']['App']['SetPlayerSpeed'](arg1);
}

export function SetPlayerVolume(arg1) {
  return window['go']['app']['App']['SetPlayerVolume'](arg1);
}

export function StopPlayer() {
  return window['go']['app']['App']['StopPlayer']();
}

export function TrashFiles(arg1, arg2, arg3) {
  return window['go']['app']['App']['TrashFiles'](arg1, arg2, arg3);
}

export function UploadFiles(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UploadFiles'](arg1, arg2, arg3, arg4);
}
