// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFavorite(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddFavorite'](arg1, arg2, arg3);
}

export function ApplyUpdate(arg1) {
  return window['go']['app']['App']['ApplyUpdate'](arg1);
}

export function CancelDownload(arg1) {
  return window['go']['app']['App']['CancelDownload'](arg1);
}

export function CancelMigrate(arg1) {
  return window['go']['app']['App']['CancelMigrate'](arg1);
}

export function CancelUpload(arg1) {
  return window['go']['app']['App']['CancelUpload'](arg1);
}

export function CheckUpdate() {
  return window['go']['app']['App']['CheckUpdate']();
}

export function ClearCache() {
  return window['go']['app']['App']['ClearCache']();
}

export function ClearDownloads() {
  return window['go']['app']['App']['ClearDownloads']();
}

export function ClearLogs() {
  return window['go']['app']['App']['ClearLogs']();
}

export function ClearMigrateJobs() {
  return window['go']['app']['App']['ClearMigrateJobs']();
}

export function ClearUploads() {
  return window['go']['app']['App']['ClearUploads']();
}

export function ClosePikPakCaptcha() {
  return window['go']['app']['App']['ClosePikPakCaptcha']();
}

export function CopyFiles(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CopyFiles'](arg1, arg2, arg3, arg4);
}

export function CreateShare(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateShare'](arg1, arg2, arg3);
}

export function DeleteDirectoryCache(arg1) {
  return window['go']['app']['App']['DeleteDirectoryCache'](arg1);
}

export function DeleteFiles(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteFiles'](arg1, arg2, arg3);
}

export function DeleteLocalTag(arg1, arg2, arg3) {
  return window['go']['app']['App']['DeleteLocalTag'](arg1, arg2, arg3);
}

export function DeleteMigrateJob(arg1) {
  return window['go']['app']['App']['DeleteMigrateJob'](arg1);
}

export function DeleteOfflineTask(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['DeleteOfflineTask'](arg1, arg2, arg3, arg4);
}

export function DeleteSyncConfig(arg1) {
  return window['go']['app']['App']['DeleteSyncConfig'](arg1);
}

export function DownloadFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['DownloadFile'](arg1, arg2, arg3);
}

export function DownloadURL(arg1, arg2, arg3) {
  return window['go']['app']['App']['DownloadURL'](arg1, arg2, arg3);
}

export function DownloadUpdate(arg1) {
  return window['go']['app']['App']['DownloadUpdate'](arg1);
}

export function ExportLogs() {
  return window['go']['app']['App']['ExportLogs']();
}

export function FavoriteFiles(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['FavoriteFiles'](arg1, arg2, arg3, arg4);
}

export function ForceQuit() {
  return window['go']['app']['App']['ForceQuit']();
}

export function GetDirectoryCache(arg1) {
  return window['go']['app']['App']['GetDirectoryCache'](arg1);
}

export function GetDownloadURL(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetDownloadURL'](arg1, arg2, arg3);
}

export function GetFileDetail(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetFileDetail'](arg1, arg2, arg3);
}

export function GetLogPath() {
  return window['go']['app']['App']['GetLogPath']();
}

export function GetPan189Captcha() {
  return window['go']['app']['App']['GetPan189Captcha']();
}

export function GetPlayCursor(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetPlayCursor'](arg1, arg2, arg3);
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetVideoPreview(arg1, arg2, arg3) {
  return window['go']['app']['App']['GetVideoPreview'](arg1, arg2, arg3);
}

export function ImportShare(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ImportShare'](arg1, arg2, arg3, arg4);
}

export function ListAccounts() {
  return window['go']['app']['App']['ListAccounts']();
}

export function ListDir(arg1, arg2, arg3) {
  return window['go']['app']['App']['ListDir'](arg1, arg2, arg3);
}

export function ListDirPage(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ListDirPage'](arg1, arg2, arg3, arg4);
}

export function ListDownloads() {
  return window['go']['app']['App']['ListDownloads']();
}

export function ListFavorites(arg1, arg2) {
  return window['go']['app']['App']['ListFavorites'](arg1, arg2);
}

export function ListLocalTags(arg1, arg2) {
  return window['go']['app']['App']['ListLocalTags'](arg1, arg2);
}

export function ListMigrateJobs() {
  return window['go']['app']['App']['ListMigrateJobs']();
}

export function ListOfflineTasks(arg1) {
  return window['go']['app']['App']['ListOfflineTasks'](arg1);
}

export function ListProviders() {
  return window['go']['app']['App']['ListProviders']();
}

export function ListShareHistory(arg1) {
  return window['go']['app']['App']['ListShareHistory'](arg1);
}

export function ListSyncConfigs() {
  return window['go']['app']['App']['ListSyncConfigs']();
}

export function ListTrash(arg1, arg2) {
  return window['go']['app']['App']['ListTrash'](arg1, arg2);
}

export function ListUploads() {
  return window['go']['app']['App']['ListUploads']();
}

export function LocalPreviewURL(arg1) {
  return window['go']['app']['App']['LocalPreviewURL'](arg1);
}

export function LogFrontend(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['LogFrontend'](arg1, arg2, arg3, arg4);
}

export function MediaProxy() {
  return window['go']['app']['App']['MediaProxy']();
}

export function MigrateFiles(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['app']['App']['MigrateFiles'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function Mkdir(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['Mkdir'](arg1, arg2, arg3, arg4);
}

export function MoveFiles(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['MoveFiles'](arg1, arg2, arg3, arg4);
}

export function OfflineDownload(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['OfflineDownload'](arg1, arg2, arg3, arg4);
}

export function OpenBrowser(arg1) {
  return window['go']['app']['App']['OpenBrowser'](arg1);
}

export function OpenFile(arg1) {
  return window['go']['app']['App']['OpenFile'](arg1);
}

export function OpenPikPakCaptcha(arg1) {
  return window['go']['app']['App']['OpenPikPakCaptcha'](arg1);
}

export function PauseDownload(arg1) {
  return window['go']['app']['App']['PauseDownload'](arg1);
}

export function PickDirectory(arg1, arg2) {
  return window['go']['app']['App']['PickDirectory'](arg1, arg2);
}

export function PickFiles(arg1) {
  return window['go']['app']['App']['PickFiles'](arg1);
}

export function PinFileSnapshot(arg1, arg2, arg3) {
  return window['go']['app']['App']['PinFileSnapshot'](arg1, arg2, arg3);
}

export function PlayVideo(arg1, arg2, arg3) {
  return window['go']['app']['App']['PlayVideo'](arg1, arg2, arg3);
}

export function PlayVideoQuality(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['PlayVideoQuality'](arg1, arg2, arg3, arg4);
}

export function PreviewURL(arg1, arg2, arg3) {
  return window['go']['app']['App']['PreviewURL'](arg1, arg2, arg3);
}

export function PrioritizeDownload(arg1) {
  return window['go']['app']['App']['PrioritizeDownload'](arg1);
}

export function ProviderLogin(arg1, arg2) {
  return window['go']['app']['App']['ProviderLogin'](arg1, arg2);
}

export function RefreshAccount(arg1) {
  return window['go']['app']['App']['RefreshAccount'](arg1);
}

export function RefreshOfflineTasks(arg1, arg2) {
  return window['go']['app']['App']['RefreshOfflineTasks'](arg1, arg2);
}

export function RemoveAccount(arg1) {
  return window['go']['app']['App']['RemoveAccount'](arg1);
}

export function RemoveDownload(arg1) {
  return window['go']['app']['App']['RemoveDownload'](arg1);
}

export function RemoveFavorite(arg1, arg2, arg3) {
  return window['go']['app']['App']['RemoveFavorite'](arg1, arg2, arg3);
}

export function RenameBatch(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RenameBatch'](arg1, arg2, arg3, arg4);
}

export function RenameFile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['RenameFile'](arg1, arg2, arg3, arg4);
}

export function RestoreFiles(arg1, arg2, arg3) {
  return window['go']['app']['App']['RestoreFiles'](arg1, arg2, arg3);
}

export function ResumeDownload(arg1) {
  return window['go']['app']['App']['ResumeDownload'](arg1);
}

export function ResumeUpload(arg1) {
  return window['go']['app']['App']['ResumeUpload'](arg1);
}

export function RevealInFolder(arg1) {
  return window['go']['app']['App']['RevealInFolder'](arg1);
}

export function RunSync(arg1) {
  return window['go']['app']['App']['RunSync'](arg1);
}

export function SaveCloudTextFile(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SaveCloudTextFile'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveDirectoryCache(arg1, arg2) {
  return window['go']['app']['App']['SaveDirectoryCache'](arg1, arg2);
}

export function SaveImportedShare(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SaveImportedShare'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveLocalTag(arg1) {
  return window['go']['app']['App']['SaveLocalTag'](arg1);
}

export function SaveMountedAccount(arg1, arg2) {
  return window['go']['app']['App']['SaveMountedAccount'](arg1, arg2);
}

export function SavePlayCursor(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SavePlayCursor'](arg1, arg2, arg3, arg4);
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SaveSyncConfig(arg1) {
  return window['go']['app']['App']['SaveSyncConfig'](arg1);
}

export function SearchFiles(arg1, arg2, arg3) {
  return window['go']['app']['App']['SearchFiles'](arg1, arg2, arg3);
}

export function SendGuangyaSms(arg1) {
  return window['go']['app']['App']['SendGuangyaSms'](arg1);
}

export function SetupFloater(arg1) {
  return window['go']['app']['App']['SetupFloater'](arg1);
}

export function SetupTray(arg1) {
  return window['go']['app']['App']['SetupTray'](arg1);
}

export function ShowMainWindow() {
  return window['go']['app']['App']['ShowMainWindow']();
}

export function StartSyncScheduler() {
  return window['go']['app']['App']['StartSyncScheduler']();
}

export function TrashFiles(arg1, arg2, arg3) {
  return window['go']['app']['App']['TrashFiles'](arg1, arg2, arg3);
}

export function UploadFiles(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['UploadFiles'](arg1, arg2, arg3, arg4, arg5);
}

export function WatchShowRequests() {
  return window['go']['app']['App']['WatchShowRequests']();
}
