#!/usr/bin/env node

import fs from 'fs'
import path from 'path'
import process from 'process'
import { fileURLToPath } from 'url'

const repoRoot = path.resolve(fileURLToPath(new URL('..', import.meta.url)))
const envFile = path.join(repoRoot, '.env.local')
const outputFile = path.join(repoRoot, 'src', 'secrets.generated.ts')

const secretNames = [
  'ONEDRIVE_CLIENT_ID',
  'ONEDRIVE_CLIENT_SECRET',
  'DROPBOX_APP_KEY',
  'DROPBOX_APP_SECRET',
  'GOOGLE_DRIVE_CLIENT_ID',
  'GOOGLE_DRIVE_CLIENT_SECRET',
  'SUBTITLE_SEARCH_API_KEY',
  'SUBTITLE_DOWNLOAD_API_KEY',
  'APPLE_ID',
  'APPLE_PASSWORD',
  'APPLE_TEAM_ID'
]

function parseArgs(argv) {
  return {
    mode: argv.find((arg) => arg.startsWith('--mode='))?.split('=')[1] || 'local',
    strict: argv.includes('--strict')
  }
}

function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {}
  const output = {}
  const text = fs.readFileSync(filePath, 'utf8')
  for (const rawLine of text.split(/\r?\n/)) {
    const line = rawLine.trim()
    if (!line || line.startsWith('#')) continue
    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$/)
    if (!match) continue
    const key = match[1]
    let value = match[2].trim()
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1)
    }
    output[key] = value.replace(/\\n/g, '\n')
  }
  return output
}

function readRequiredNames() {
  const raw = process.env.REQUIRED_RELEASE_SECRETS || ''
  return raw
    .split(',')
    .map((name) => name.trim())
    .filter(Boolean)
}

function main() {
  const args = parseArgs(process.argv.slice(2))
  const localEnv = args.mode === 'ci' ? {} : parseEnvFile(envFile)
  const values = {}

  for (const name of secretNames) {
    values[name] = process.env[name] ?? localEnv[name] ?? ''
  }

  const required = args.strict ? readRequiredNames() : []
  const missing = required.filter((name) => !values[name])
  if (missing.length) {
    console.error(`Missing required release secrets: ${missing.join(', ')}`)
    process.exit(1)
  }

  const lines = [
    '// This file is generated by scripts/generate-secrets.mjs.',
    '// Do not edit manually. Do not commit real secret values.',
    ''
  ]

  for (const name of secretNames) {
    lines.push(`export const ${name} = ${JSON.stringify(values[name])}`)
  }
  lines.push('')

  fs.mkdirSync(path.dirname(outputFile), { recursive: true })
  fs.writeFileSync(outputFile, lines.join('\n'), 'utf8')

  const filled = secretNames.filter((name) => values[name]).length
  console.log(`Generated src/secrets.generated.ts (${filled}/${secretNames.length} values set, mode=${args.mode})`)
}

main()
